# Generated by Django 3.1.5 on 2025-02-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0002_moduleaccess'),
        ('globals', '0002_auto_20241007_2302'),
    ]

    operations = [
    ]
