# Generated by Django 3.1.5 on 2025-02-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_cms', '0002_auto_20241023_1002'),
        ('online_cms', '0002_auto_20241012_1459'),
    ]

    operations = [
    ]
